name: nyc_collisions
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12.3
    - black=24.4.2
    - coverage=7.2.2
    - folium=0.14.0
    - geopandas=0.14.2
    - jupyter=1.0.0
    - matplotlib=3.8.4
    - nbqa=1.8.5
    - notebook=7.0.8
    - numpy=1.26.4
    - pandas=2.2.1
    - pip=24.0
    - pydocstyle=6.3.0
    - pylint=3.2.2
    - pytest=7.4.4
    - scikit-learn=1.4.2
    - scipy=1.13.1
    - shapely=2.0.1
    - pip:
        - panda-helper==0.0.2
