name: nyc_collisions
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.9.12
    - black=19.10b0
    - folium=0.12.1.post1
    - geopandas=0.9.0
    - jupyter=1.0.0
    - matplotlib=3.5.1
    - nbqa=1.3.1
    - notebook=6.4.11
    - pandas=1.4.2
    - pip=21.2.4
    - pydocstyle=6.1.1
    - pylint=2.12.2
    - pytest=7.1.2
    - scikit-learn=1.0.2
    - scipy=1.7.3
    - shapely=1.7.1
    - pip:
        - panda-helper==0.0.2
