name: nyc_collisions
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - beautifulsoup4=4.12.3
    - black=24.4.2
    - codespell
    - coverage=7.2.2
    - folium=0.14.0
    - geopandas=0.14.2
    - jupyter=1.0.0
    - matplotlib=3.8.4
    - nbqa=1.8.5
    - notebook=7.0.8
    - numpy=1.26.4
    - pandas=2.2.2
    - pip=24.0
    - pre-commit=3.4.0
    - pydocstyle=6.3.0
    - pylint=3.2.2
    - pytest=7.4.4
    - requests=2.32.2
    - ruff=0.3.5
    - scikit-learn=1.4.2
    - scipy=1.13.1
    - seaborn=0.13.2
    - shapely=2.0.1
    - statsmodels=0.14.2
    - xgboost=2.0.3
    - pip:
        - panda-helper==0.1.1
