name: nyc_collisions
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8.12
    - black=19.10b0
    - folium=0.12.1.post1
    - geopandas=0.9.0
    - jupyter=1.0.0
    - matplotlib=3.5.1
    - notebook=6.4.5
    - pandas=1.3.3
    - pip=21.1.3
    - pytest=6.2.4
    - scikit-learn=1.0.1
    - scipy=1.7.1
    - shapely=1.8.0
    - pip:
        - panda-helper==0.0.2